<?php

class m140920_225016_insert_dummy_data_for_posts extends CDbMigration
{
	public function safeUp()
	{
		$this->execute("
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-1', 'Test Post 1', 'Kratki tekst nekog posta bla bla', 'Praesent mollis lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-2', 'Test Post 2', 'Kratki tekst nekog posta bla bla', 'Praesent mollis lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-3', 'Test Post 3', 'Kratki tekst nekog posta bla bla', 'Praesent mollis lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-4', 'Test Post 4', 'Kratki tekst nekog posta bla bla', 'Praesent mollis drugacije test nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-5', 'Test Post 5', 'Kratki tekst nekog posta bla bla', 'Praesent mollis dummy data nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-6', 'Test Post 6', 'Kratki tekst nekog posta bla bla', 'Praesent mollis hehe klosaru nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-7', 'Test Post 7', 'Kratki tekst nekog posta bla bla', 'Praesent mollis neke jadi nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-8', 'Test Post 8', 'Kratki tekst nekog posta bla bla', 'Praesent mollis nemoj da se hladis nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-9', 'Test Post 9', 'Kratki tekst nekog posta bla bla', 'Praesent mollis sad bi golub sam sebe... nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-10', 'Test Post 10', 'Kratki tekst nekog posta bla bla', 'Praesent mollis test nest lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-11', 'Test Post 11', 'Kratki tekst nekog posta bla bla', 'Praesent mollis lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-12', 'Test Post 12', 'Kratki tekst nekog posta bla bla', 'Praesent mollis lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-13', 'Test Post 13', 'Kratki tekst nekog posta bla bla', 'Praesent Lalalala nemam sta pametno da pisem lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-14', 'Test Post 14', 'Kratki tekst nekog posta bla bla', 'Praesent mollis lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-15', 'Test Post 15', 'Kratki tekst nekog posta bla bla', 'Praesent mollis lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-16', 'Test Post 16', 'Kratki tekst nekog posta bla bla', 'Praesent Evo jos malo lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-17', 'Test Post 17', 'Kratki tekst nekog posta bla bla', 'Praesent mollis lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);
			INSERT INTO sl_blog_post (urlLink, name, shortText, fullArticle, entryDate, isVisible, authorId, tags) VALUES ('test-post-18', 'Test Post 18', 'Kratki tekst nekog posta bla bla', 'Praesent Kraaaaaj :) lacus nisi, a interdum lacus aliquet ac. Aenean aliquam tellus ante, vel faucibus velit condimentum id. Proin non quam vel lacus molestie aliquet. Morbi vehicula tellus augue, vel aliquam felis egestas in. Vivamus venenatis sapien arcu, at fringilla augue placerat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse faucibus sapien quis tellus lobortis, ac mattis urna facilisis. Fusce ante libero, consequat ut vestibulum eu, sollicitudin eget tellus. Nullam vehicula interdum pharetra. Phasellus pellentesque viverra finibus. Aliquam erat volutpat. Ut mattis sem vitae lectus tristique, ac pellentesque sapien malesuada. Ut aliquam felis id porta aliquam.', NULL, '1', '1', NULL);

		");
	}

	public function safeDown()
	{
		$this->execute("
			TRUNCATE sl_blog_posts;
		");
	}
}